### ISSUE TITLE
Worlds BETA

### ISSUE THREAD

**Issue by pentreathm** [decentraland/worlds-content-server#12]
Backend 
- [x] Scene Limit for deployments and hosting - size (n x m)
- [x] Scene Limit for deployments and hosting - total weight and weight per parcel (Mb)
- [x] Implement a friendly URL play.decentraland.org/world/NAME and access through &world=NAME
- [x] Implement protocol message for MAX number of concurrent users (currently 100 is the max) 
- [x] Debugging Metrics endpoint to know how many Worlds are deployed in the server 
- [x] Implement a white list mechanism to bypass validations for specific NAMEs 
- [x] Expose qty of users connected to Worlds from the ws-room-service to the catalyst monitor
- [x] Stress test for the ws-room-service. Find out the limit of users that it can host 
- [x] Return 404 if the world is not found
